insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Mushroom - Morel Frozen', 883.6);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Carbonated Water - Wildberry', 887.88);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Balbach Riverside', 982.56);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Foil Wrap', 488.79);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Mace Ground', 269.62);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pancetta', 810.9);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Turkey - Ground. Lean', 556.08);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Lamb - Leg, Bone In', 542.01);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Glycerine', 629.19);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Scallop - St. Jaques', 443.47);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Bandage - Flexible Neon', 69.81);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pepper - Chili Powder', 641.35);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cabbage Roll', 540.33);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Dome Lid Clear P92008h', 926.33);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pastry - Apple Muffins - Mini', 288.19);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Southern Comfort', 223.95);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Initation Crab Meat', 522.14);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Laundry - Bag Cloth', 835.62);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Veal - Brisket, Provimi,bnls', 65.09);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Tarragon - Primerba, Paste', 557.2);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Milk - 2% 250 Ml', 997.84);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Flour - Bran, Red', 182.36);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Plasticspoonblack', 325.41);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Towel Dispenser', 433.21);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Corn Meal', 199.41);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Puree - Kiwi', 228.25);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pork - Belly Fresh', 273.62);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pasta - Fett Alfredo, Single Serve', 604.85);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Mushroom - Morel Frozen', 883.6);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Curry Powder', 791.53);
